# Generated by Django 6.0.1 on 2026-02-01 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_show_time_alter_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Event', 'Event'), ('Play', 'Play'), ('Stream', 'Stream')], default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
    ]
