# Generated by Django 6.0.1 on 2026-02-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_booking_booking_type_booking_details_booking_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Event', 'Event'), ('Play', 'Play'), ('Stream', 'Stream')], default='Movie', max_length=20),
        ),
    ]
