# Generated by Django 6.0.1 on 2026-02-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_booking_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
