# Generated by Django 6.0.1 on 2026-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_booking_seats_alter_booking_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Event', 'Event'), ('Play', 'Play'), ('Stream', 'Stream')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
