# Generated by Django 6.0.1 on 2026-02-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_title_movie_about_movie_banner_movie_cast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
