# Generated by Django 6.0.1 on 2026-02-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_booking_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='show_date',
            field=models.DateField(blank=True, help_text='Show date', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly unique identifier', unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Booking creation timestamp'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='details',
            field=models.TextField(blank=True, help_text='Additional booking details'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=0, help_text='Total price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.CharField(blank=True, help_text='Comma-separated seat list', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.CharField(blank=True, help_text='Show time (e.g., 6:00 PM)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, help_text='Movie/Event/Play title', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='about',
            field=models.TextField(blank=True, help_text='Movie description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.CharField(blank=True, help_text='Path to banner image', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.JSONField(blank=True, default=list, help_text="Cast info: [{'name':'', 'role':'', 'image':''}]"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.JSONField(blank=True, default=list, help_text='Formats like 2D, 3D'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Available languages'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, help_text='Path to poster image', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0, help_text='Movie rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Movie title', max_length=200),
        ),
    ]
