# Generated by Django 6.0.1 on 2026-02-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_booking_show_date_movie_slug_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Used', 'Used'), ('Pending', 'Pending')], default='Confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='banner',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
